export { DOMMutationPlugin } from "./dom"
export { CLSPlugin } from "./cls"
export { FPPlugin } from "./fp"
export { FCPPlugin } from "./fcp"
export { WebVitalsPlugin } from "./web-vitals"
export { TimingPlugin } from "./timing"